name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  swift-build:
    name: Swift build
    runs-on: macos-15

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install espeak-ng
        run: brew install espeak-ng

      - name: Build
        run: swift build
